### ISSUE TITLE
2020-01-14 Library Scanathon.md not showing

### ISSUE THREAD

**Issue by osc-galway** [Open-Scholarship-Community-Galway/Open-Scholarship-Community-Galway.github.io#3]
I don't know why the new event "2020-01-14 Library Scanathon.md" does not show on website. What am I missing?

**Comment by Kevin-Mattheus-Moerman** [comment]
Apparently you need a hyphen in the name between the date and the subsequent text, i.e. this is wrong:
`2020-01-14 Library Scanathon.md`
This is correct:
`2020-01-14-Library Scanathon.md`
